[package]
name = "hyper_cgi"
version = "0.1.0"
authors = ["Christian Schilling <christian.schilling@esrlabs.com>", "Louis-Marie Givel <louis-marie.givel@esrlabs.com>"]
edition = "2018"
license-file = "LICENSE"
description = "Run CGI scripts with hyper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "*"
tokio = {version = "*", features = ["full"] }
tokio-util = { version = "0.3.1", features=["compat"] }
hyper = "*"

[lib]
name = "hyper_cgi"
path = "src/hyper_cgi.rs"
